services:
#    koombea_blogs_train_notebook:
#        build: 
#            context: .
#            dockerfile: Dockerfile.notebook
#        volumes: 
#            - type: bind
#              source: .
#              target: /home/koombea
#        env_file: 
#            - ./vars.staging.env
#            - ./vars.env
#        environment: 
#            - JUPYTER_ENABLE_LAB=yes
#        networks:
#            - koombea_blogs_train_net
#        ports:
#            - 8888:8888
#        entrypoint: 
#            - jupyter
#            - lab
#            - "--port=8888"
#            - "--no-browser"
#            - "-ip=0.0.0.0"
#            - --allow-root

    koombea_blogs_train_component:
        build: 
            context: .
            dockerfile: Dockerfile
        env_file: 
            - ./vars.staging.env
            - ./vars.env
        networks:
            - koombea_blogs_train_net
        volumes: 
            - type: bind
              source: .
              target: /opt/ml/code

networks:
    koombea_blogs_train_net:
